name: 'Lint workflows'
on:
  push:
    paths:
      - '.github/workflows/*'
jobs:
  lint_workflows:
    name: 'Run actionlint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Add problem matcher'
        run: echo "::add-matcher::.github/actionlint-matcher.json"

      - name: 'Install actionlint'
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: 'Run actionlint'
        run: ./actionlint -color
