name: 'Create release'
on:
  push:
    tags:
      - 'v*'
jobs:
  create_release:
    name: 'Create release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref }} \
            --repo="${{ github.repository }}" \
            --title "Release ${{ github.ref }}" \
            --generate-notes \
            --draft
